### ISSUE TITLE
How to run on specific folder

### ISSUE THREAD

**Issue by guillaume-docquier-vention** [djdefi/cloc-action#26]
Hi!
I want to use this action in my monorepo, but only for a specific project (folder). I noticed that the action ran from the root, so it read all the other projects.

Is it possible to specify a working directory?

**Comment by Bleskocvok** [comment]
I also wanted to run `cloc` only on a select few directories, so as a workaround I had to exclude all the other ones using `--exclude-dir` or `--fullpath --not-match-d`.

It would be better if this action provided access to the `cloc` command itself. For instance, like [hrishikesh-kadam/setup-lcov](https://github.com/hrishikesh-kadam/setup-lcov) does for `lcov`. So, it could be used like this:
```yml
- uses: djdefi/cloc-action@main
- run: cloc folder/src other-folder/src
```

**Comment by guillaume-docquier-vention** [comment]
I made it work like so:
```
- name: Count Lines of Code
  uses: djdefi/cloc-action@6
  with:
    options: client/ --vcs git --json --report-file=./client/${{ env.CLOC_OUTPUT_PATH }}
```

The options get passed to `cloc`. See: https://github.com/djdefi/cloc-action/blob/main/entrypoint.sh#L4
The key thing was to add `--vcs git` after the folder, otherwise it would read all files including those ignored by git.
