### ISSUE TITLE
Exclude file isn't working

### ISSUE THREAD

**Issue by maiconsanson** [djdefi/cloc-action#28]
Hello, thanks for the `cloc-action`.

What am I missing here to exclude a file to be counted?
Neither `--exclude-list-file` nor `--not-match-f` seems to work.

Locally, it is working great as always. 🤡 
`github.com/AlDanial/cloc v 2.02`

For example, I want to exclude the `pnpm-lock.yaml` from being counted and I have something like these:

```yaml
- name: Count Lines of Code with additional options
        uses: djdefi/cloc-action@main
        with:
          options: |
            --exclude-dir=node_modules,public \
            --not-match-f="pnpm-lock\.yaml" \
            --quiet --hide-rate --skip-uniqueness --fullpath --md \
            --report-file=.github/workflows/cloc_stats.md \
```

The `--exclude-dir` param is working using folders as expected.

Thanks for any suggestions.
